apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reminder-api.fullname" . }}-mysql-secret
  labels:
    {{- include "reminder-api.labels" . | nindent 4 }}
data:
  DB_USERNAME: {{ .Values.mysql.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  DB_NAME: {{ .Values.mysql.database | b64enc | quote }}
type: Opaque
