nameOverride: ""
fullnameOverride: ""

#set the replica count
replicaCount: 1

image:
  repository: ghcr.io/prasanna12510/reminder-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  DB_HOST: mysql.mysql.svc.cluster.local #internal k8s domain name
  DB_PORT: 3306

#sets mysql env variable
mysql:
  username: reminder_user
  password: reminder_pass
  database: reminder

#image pull secrets
imagePullSecrets:
  - name: dockerconfigjson-github-com

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ingress:
  enabled: true
  path: /

# ensure the exposed docker port is exposed via service
service:
  type: NodePort
  name: http
  port: 8080
  targetPort: 8080

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

liveness:
  httpGet:
    path: /
    port: http
  timeoutSeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  initialDelaySeconds: 60

readiness:
  httpGet:
    path: /
    port: http
  timeoutSeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  initialDelaySeconds: 60

# to ensure availability
disruptionBudget:
  minAvailable: 1

volumeMounts: []

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}
